version: '3.1'

services:
  pg:
    image: postgres
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intelcia
    volumes:
      - ./postgres-storage:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8080:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: intelcia@postgres.com
      PGADMIN_DEFAULT_PASSWORD: postgres
